<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class PersonFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
					'name' => $this->faker->randomElement([
						'Leonardo DiCaprio',
						'Brad Pitt',
						'Angelina Jolie',
						'Tom Hanks',
						'Meryl Streep',
						'Johnny Depp',
						'Scarlett Johansson',
						'Robert Downey Jr.',
						'Jennifer Lawrence',
						'George Clooney',
						'Natalie Portman',
						'Matt Damon',
						'Emma Stone',
						'Will Smith',
						'Charlize Theron',
						'Chris Hemsworth',
						'Anne Hathaway',
						'Ryan Reynolds',
						'Sandra Bullock',
						'Christian Bale',
						'Julia Roberts',
						'Tom Cruise',
						'Nicole Kidman',
						'Mark Wahlberg',
						'Cate Blanchett',
						'Keanu Reeves',
						'Jessica Chastain',
						'Samuel L. Jackson',
						'Margot Robbie',
						'Joaquin Phoenix',
						'Emily Blunt',
						'Ben Affleck',
						'Gal Gadot',
						'Chris Evans',
						'Viola Davis',
						'Ryan Gosling',
						'Brie Larson',
						'Daniel Craig',
						'Emma Watson',
						'Michael Fassbender',
						'Zoe Saldana',
						'Jake Gyllenhaal',
						'Salma Hayek',
						'Chris Pratt',
						'Rachel McAdams',
						'Idris Elba',
						'Kate Winslet',
						'Javier Bardem',
						'Michelle Williams',
						'Jared Leto',
						'Helena Bonham Carter',
						'Adam Driver',
						'Octavia Spencer',
						'Shailene Woodley',
						'Mahershala Ali',
						'Kristen Stewart',
						'Timothée Chalamet',
						'Zendaya',
						'Rami Malek',
						'Florence Pugh',
						'John Boyega',
						'Anya Taylor-Joy',
						'Dev Patel',
						'Awkwafina',
						'Tom Hardy',
						'Rosamund Pike',
						'Andrew Garfield',
						'Jessica Alba',
						'Paul Rudd',
						'Chadwick Boseman',
						'Elizabeth Olsen',
						'Jason Momoa',
						'Melissa McCarthy',
						'John Krasinski',
						'Emily VanCamp',
						'Chris Pine',
						'Gina Rodriguez',
						'Pedro Pascal',
						'Millie Bobby Brown',
						'David Harbour',
						'Winona Ryder',
						'Finn Wolfhard',
						'Gaten Matarazzo',
						'Caleb McLaughlin',
						'Noah Schnapp',
						'Sadie Sink',
						'Dacre Montgomery',
						'Natalia Dyer',
						'Charlie Heaton',
						'Cara Buono',
						'Joe Keery',
						'Maya Hawke',
						'Priah Ferguson',
						'Brett Gelman',
						'Sean Astin',
						'Paul Reiser',
						'Matthew Modine',
						'Robert Englund'
					]),
        ];
    }
}
